/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi;

/**
 *
 * @author Widiana
 */
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
public class profil extends javax.swing.JFrame {

    /**
     * Creates new form profil
     */
    public profil() {
        initComponents();
        Connect();
        Loadprofilid();
        
         this.setLocationRelativeTo(null);
         
    }
        Connection con;
        PreparedStatement pst;
        ResultSet rs;
    public void Connect() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/aplikasi", "root", "");
            } catch (Exception e) {
                Logger.getLogger(profil.class.getName()).log(Level.SEVERE, null, e);
            }
        } catch (Exception e) {
            Logger.getLogger(profil.class.getName()).log(Level.SEVERE, null, e);
        }
    }
     public void Loadprofilid() {
         try {
             pst =con.prepareStatement("select id from profil");
             rs =pst.executeQuery();
             tidp.removeAllItems();
             while(rs.next()){
                 tidp.addItem(rs.getString(1).toString());
             }
             
             
         } catch (Exception e) {
            Logger.getLogger(profil.class.getName()).log(Level.SEVERE, null, e);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbiop = new javax.swing.JTextField();
        tnop = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tnamap = new javax.swing.JTextField();
        tnewp = new javax.swing.JButton();
        tdeletp = new javax.swing.JButton();
        tidp = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tviewp = new javax.swing.JButton();
        taddp = new javax.swing.JButton();
        teditp = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jTextField2.setBackground(new java.awt.Color(204, 204, 255));

        jPasswordField1.setBackground(new java.awt.Color(255, 204, 204));

        jTextField3.setBackground(new java.awt.Color(204, 204, 255));
        jTextField3.setForeground(new java.awt.Color(51, 51, 255));
        jTextField3.setText("YYYY-DD-MM");

        jTextField4.setBackground(new java.awt.Color(204, 204, 255));
        jTextField4.setForeground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Nama");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("UsetName");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Password");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Tanggal Lahir");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Email");

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setText("Sing UP");

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton2.setText("Cancle");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Exotc350 DmBd BT", 1, 18)); // NOI18N
        jLabel2.setText("Profil");

        tbiop.setBackground(new java.awt.Color(204, 204, 255));

        tnop.setBackground(new java.awt.Color(204, 204, 255));
        tnop.setForeground(new java.awt.Color(51, 51, 255));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Nama Lengkap");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("Bio");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setText("No Telpon");

        tnamap.setBackground(new java.awt.Color(204, 204, 255));

        tnewp.setBackground(new java.awt.Color(204, 204, 0));
        tnewp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tnewp.setText("New");
        tnewp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnewpActionPerformed(evt);
            }
        });

        tdeletp.setBackground(new java.awt.Color(255, 102, 102));
        tdeletp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tdeletp.setText("Delet");
        tdeletp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdeletpActionPerformed(evt);
            }
        });

        tidp.setBackground(new java.awt.Color(204, 204, 255));
        tidp.setForeground(new java.awt.Color(0, 0, 0));
        tidp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");

        tviewp.setBackground(new java.awt.Color(102, 102, 255));
        tviewp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tviewp.setText("View");
        tviewp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tviewpActionPerformed(evt);
            }
        });

        taddp.setBackground(new java.awt.Color(102, 204, 0));
        taddp.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        taddp.setText("add");
        taddp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taddpActionPerformed(evt);
            }
        });

        teditp.setBackground(new java.awt.Color(102, 102, 255));
        teditp.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        teditp.setText("Edit");
        teditp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teditpActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/awan afatar.png"))); // NOI18N

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/awan afatar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tnewp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(taddp)
                                .addGap(18, 18, 18)
                                .addComponent(teditp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tdeletp)
                                    .addComponent(tnop, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel14))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3))
                .addGap(98, 98, 98)
                .addComponent(tidp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(tviewp)
                .addGap(49, 49, 49))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(72, 72, 72)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tbiop, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                        .addComponent(tnamap, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                    .addGap(73, 73, 73)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2)))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tidp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tviewp))
                    .addComponent(jLabel3))
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tnop, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taddp)
                    .addComponent(tnewp)
                    .addComponent(teditp)
                    .addComponent(tdeletp))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel15)))
                .addGap(292, 292, 292))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tnamap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tbiop, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addContainerGap(704, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tnewpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnewpActionPerformed
        // TODO add your handling code here:
        tnamap.setText("");
        tbiop.setText("");
        tnop.setText("");
        
        tnamap.requestFocus();
    }//GEN-LAST:event_tnewpActionPerformed

    private void taddpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taddpActionPerformed
        // TODO add your handling code here:
        try {
            String namalkp =tnamap.getText();
             String bio =tbiop.getText();
             String notelp =tnop.getText();
             pst = con.prepareStatement("INSERT INTO crud(`nama_lengkap`, `bio`, `no_telpon`) VALUES (?,?,?)");
             pst.setString(1, namalkp);
             pst.setString(2, bio);
             pst.setString(3, notelp);
             
             int k = pst.executeUpdate();

            if (k == 1) {
                JOptionPane.showMessageDialog(null, "data berhasil di tambahkan");
            } else {
                JOptionPane.showMessageDialog(null, "data gagal di tambahkan");
            }


        } catch (Exception e) {
             Logger.getLogger(profil.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_taddpActionPerformed

    private void teditpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teditpActionPerformed
        // TODO add your handling code here:
        String id =tidp.getSelectedItem().toString();
        try {
            String namalkp =tnamap.getText();
             String bio =tbiop.getText();
             String notelp =tnop.getText();
             
            pst =con.prepareStatement("UPDATE crud SET nama_lengkap=?,bio=?,no_telpon=? WHERE id=?");
            pst.setString(1, namalkp);
            pst.setString(2, bio);
            pst.setString(3, notelp);
            pst.setString(4, id);
            int k = pst.executeUpdate();

            if (k == 1) {
                JOptionPane.showMessageDialog(null, "data berhasil di edit");
                
                tnamap.setText("");
                tbiop.setText("");
                tnop.setText("");
                tnamap.requestFocus();
                Loadprofilid();
            } else {
                JOptionPane.showMessageDialog(null, "data gagal di edit");
            }
        } catch (Exception e) {
            Logger.getLogger(profil.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_teditpActionPerformed

    private void tdeletpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdeletpActionPerformed
        // TODO add your handling code here:
        try {
            String id =tidp.getSelectedItem().toString();
            pst=con.prepareStatement("DELETE FROM crud WHERE id=? ");
            pst.setString(1, id);
            
             int k = pst.executeUpdate();

            if (k == 1) {
                JOptionPane.showMessageDialog(null, "data berhasil di hapus");
                
                tnamap.setText("");
                tbiop.setText("");
                tnop.setText("");
                tnamap.requestFocus();
                Loadprofilid();
            } else {
                JOptionPane.showMessageDialog(null, "data gagal di hapus");
            }
            
        } catch (Exception e) {
            Logger.getLogger(profil.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_tdeletpActionPerformed

    private void tviewpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tviewpActionPerformed
        // TODO add your handling code here:
        try {
            String id =tidp.getSelectedItem().toString();
            pst=con.prepareStatement("SELECT * FROM crud WHERE id=? ");
            pst.setString(1, id);
            rs =pst.executeQuery();
            
            if (rs.next()==true){
                tnamap.setText(rs.getString(2));
                tbiop.setText(rs.getString(3));
                tnop.setText(rs.getString(4));
            }
            
        } catch (Exception e) {
            Logger.getLogger(profil.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_tviewpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton taddp;
    private javax.swing.JTextField tbiop;
    private javax.swing.JButton tdeletp;
    private javax.swing.JButton teditp;
    private javax.swing.JComboBox<String> tidp;
    private javax.swing.JTextField tnamap;
    private javax.swing.JButton tnewp;
    private javax.swing.JTextField tnop;
    private javax.swing.JButton tviewp;
    // End of variables declaration//GEN-END:variables

    

   
}
